# Generated by Django 4.0.4 on 2023-03-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0002_initial'),
        ('red_ferroviaria', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioncambio',
            name='cambiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='red_ferroviaria.cambiador'),
        ),
        migrations.AddField(
            model_name='intervencionvehiculo',
            name='punto_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='red_ferroviaria.puntored'),
        ),
        migrations.AddField(
            model_name='intervencionvehiculo',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.vehiculo'),
        ),
        migrations.AddField(
            model_name='intervencioneavm',
            name='EAVM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.eavm'),
        ),
        migrations.AddField(
            model_name='intervencioneavm',
            name='punto_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='red_ferroviaria.puntored'),
        ),
        migrations.AddField(
            model_name='eventovehiculo',
            name='circulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.circulacionvehiculo'),
        ),
        migrations.AddField(
            model_name='eventovehiculo',
            name='punto_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='red_ferroviaria.puntored'),
        ),
        migrations.AddField(
            model_name='eventovehiculo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.vehiculo'),
        ),
        migrations.AddField(
            model_name='eventoeavm',
            name='EAVM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.eavm'),
        ),
        migrations.AddField(
            model_name='eventoeavm',
            name='circulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.circulacioneavm'),
        ),
        migrations.AddField(
            model_name='eventoeavm',
            name='en_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='material.vehiculo'),
        ),
        migrations.AddField(
            model_name='eventoeavm',
            name='punto_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='red_ferroviaria.puntored'),
        ),
        migrations.AddField(
            model_name='circulacionvehiculo',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.vehiculo'),
        ),
        migrations.AddField(
            model_name='circulacioneavm',
            name='EAVM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.eavm'),
        ),
        migrations.AddField(
            model_name='circulacioneavm',
            name='en_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='material.vehiculo'),
        ),
        migrations.AddField(
            model_name='cambioeavm',
            name='EAVM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.eavm'),
        ),
        migrations.AddField(
            model_name='cambioeavm',
            name='cambiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='red_ferroviaria.cambiador'),
        ),
        migrations.AddField(
            model_name='cambioeavm',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.operacioncambio'),
        ),
        migrations.AddField(
            model_name='alarmavehiculo',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.vehiculo'),
        ),
        migrations.AddField(
            model_name='alarmaeavm',
            name='EAVM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.eavm'),
        ),
        migrations.AddField(
            model_name='alarmacambiador',
            name='cambiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='red_ferroviaria.cambiador'),
        ),
    ]
