# Generated by Django 4.0.4 on 2023-03-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('num_niveles', models.IntegerField(blank=True, default=3, null=True)),
                ('slug_pm', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('slug_ft', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('slug_itm', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('slug_iu', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionCambiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('anchos', models.CharField(choices=[('UIC-IB', 'UIC(1435) <> IBÉRICO (1668)'), ('UIC-RUS', 'UIC(1435) <> RUSO (1520)'), ('METR-UIC', 'MÉTRICO(1000) <> UIC(1435)')], default='UIC-IB', max_length=12)),
                ('longitud_desencerrojado', models.FloatField(default=6000)),
                ('longitud_cambio_rueda', models.FloatField(default=6000)),
                ('longitud_encerrojado', models.FloatField(default=6000)),
                ('longitud_total', models.FloatField(default=36000)),
                ('fecha_aprovacion', models.DateField(blank=True, null=True)),
                ('fecha_certificacion', models.DateField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.aprovador')),
                ('certificador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.certificador')),
                ('diseñador', models.ForeignKey(limit_choices_to={'de_cambiadores': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.diseñador')),
                ('fabricante', models.ForeignKey(blank=True, limit_choices_to={'de_cambiadores': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(choices=[('LOC', 'Locomotora de línea'), ('VAG', 'Vagón de mercancías remolcado'), ('MRA', 'Material Rodante Auxiliar')], default='MRA', max_length=16)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_uic', models.CharField(blank=True, max_length=4, null=True)),
                ('serie_uic', models.CharField(blank=True, max_length=4, null=True)),
                ('num_bogies', models.IntegerField(blank=True, default=0, null=True)),
                ('imagen', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('slug_ft', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('slug_iu', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.planmantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEAVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('anchos', models.CharField(choices=[('UIC-IB', 'UIC(1435) <> IBÉRICO (1668)'), ('UIC-RUS', 'UIC(1435) <> RUSO (1520)'), ('UIC-RUS-IB', 'UIC <> RUSO <> IBÉRICO'), ('METR-UIC', 'MÉTRICO(1000) <> UIC(1435)'), ('UIC', 'UIC (1435)'), ('IB', 'IB (1668)')], default='UIC-IB', max_length=12)),
                ('fecha_aprovacion', models.DateField(blank=True, null=True)),
                ('fecha_certificacion', models.DateField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('slug_ft', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('slug_iu', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.aprovador')),
                ('certificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.certificador')),
                ('diseñador', models.ForeignKey(limit_choices_to={'de_ejes': True}, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.diseñador')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.planmantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoConjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('slug_ft', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('slug_itm', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('slug_iu', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tiposistema')),
            ],
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('slug_ft', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipoconjunto')),
            ],
        ),
        migrations.CreateModel(
            name='SistemasVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tiposistema')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='SistemasEAVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EAVM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipoeavm')),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tiposistema')),
            ],
        ),
        migrations.CreateModel(
            name='NivelesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nivel', models.IntegerField(blank=True, default=0, null=True)),
                ('cod_nivel', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('dias_siguiente', models.IntegerField(default=365)),
                ('km_siguiente', models.IntegerField(default=100000)),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.planmantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='InstruccionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('definicion', models.CharField(max_length=50, unique=True)),
                ('n1', models.BooleanField(default=True)),
                ('n2', models.BooleanField(default=True)),
                ('n3', models.BooleanField(default=True)),
                ('n4', models.BooleanField(default=True)),
                ('n5', models.BooleanField(default=True)),
                ('descripcion', models.CharField(max_length=300, unique=True)),
                ('valor_min', models.FloatField(blank=True, null=True)),
                ('valor_max', models.FloatField(blank=True, null=True)),
                ('unidades_medida', models.CharField(blank=True, max_length=6, null=True)),
                ('slug_it', models.CharField(blank=True, default=' ', max_length=30, null=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipocomponente')),
            ],
        ),
    ]
