# Generated by Django 4.1.7 on 2023-03-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovehiculo',
            name='carga_maxima',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='peso_x_eje',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='tara',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='velocidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
