# Generated by Django 4.1.7 on 2023-03-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0002_tipovehiculo_carga_maxima_tipovehiculo_longitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrucciontecnica',
            name='slug_it',
        ),
        migrations.RemoveField(
            model_name='planmantenimiento',
            name='slug_pm',
        ),
        migrations.RemoveField(
            model_name='tipocomponente',
            name='slug_ft',
        ),
        migrations.RemoveField(
            model_name='tipoconjunto',
            name='slug_ft',
        ),
        migrations.RemoveField(
            model_name='tipoconjunto',
            name='slug_itm',
        ),
        migrations.RemoveField(
            model_name='tipoconjunto',
            name='slug_iu',
        ),
        migrations.RemoveField(
            model_name='tipoeavm',
            name='slug_ft',
        ),
        migrations.RemoveField(
            model_name='tipoeavm',
            name='slug_iu',
        ),
        migrations.RemoveField(
            model_name='tiposistema',
            name='slug_ft',
        ),
        migrations.RemoveField(
            model_name='tiposistema',
            name='slug_itm',
        ),
        migrations.RemoveField(
            model_name='tiposistema',
            name='slug_iu',
        ),
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='slug_ft',
        ),
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='slug_iu',
        ),
    ]
