# Generated by Django 4.0.4 on 2023-03-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0001_initial'),
        ('ingenieria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('num_uic', models.CharField(blank=True, default='', max_length=17, null=True, unique=True)),
                ('km_origen', models.FloatField(default=0)),
                ('fecha_origen', models.DateField(default='2022-01-01')),
                ('fecha_fab', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('km_proximo_mant', models.FloatField(default=0)),
                ('nivel_proximo_mant', models.IntegerField(default=0)),
                ('en_servicio', models.BooleanField(default=True)),
                ('en_mantenimiento', models.BooleanField(default=True)),
                ('en_circulacion', models.BooleanField(default=True)),
                ('observaciones_servicio', models.CharField(default='sin observaciones', max_length=80)),
                ('alarma_temp', models.BooleanField(default=False)),
                ('alarma_aceleraciones', models.BooleanField(default=False)),
                ('alarma_cambio', models.BooleanField(default=False, null=True)),
                ('alarma_mantenimiento', models.BooleanField(default=False, null=True)),
                ('tempa', models.FloatField(blank=True, default=25.0, null=True)),
                ('tempb', models.FloatField(blank=True, default=25.0, null=True)),
                ('lng', models.FloatField(default=-3.982)),
                ('lat', models.FloatField(default=40.2951)),
                ('num_cambios', models.IntegerField(default=0)),
                ('km_totales', models.FloatField(default=0)),
                ('coef_trabajo', models.FloatField(default=0)),
                ('EEM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.eem')),
                ('fabricante', models.ForeignKey(blank=True, limit_choices_to={'de_ejes': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.fabricante')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.keeper')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.owner')),
                ('tipo_EAVM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.tipoeavm')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_uic', models.CharField(blank=True, default='', max_length=17, null=True, unique=True)),
                ('descripcion_particular', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('km_origen', models.FloatField(default=0)),
                ('fecha_origen', models.DateField(default='2022-01-01')),
                ('fecha_fab', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('km_ultimo_mant', models.FloatField(blank=True, default=0, null=True)),
                ('km_proximo_mant', models.FloatField(blank=True, default=0, null=True)),
                ('nivel_proximo_mant', models.IntegerField(default=0)),
                ('en_servicio', models.BooleanField(default=True)),
                ('en_mantenimiento', models.BooleanField(default=True)),
                ('en_circulacion', models.BooleanField(default=True)),
                ('en_nudo', models.BooleanField(default=False)),
                ('transmitiendo', models.BooleanField(default=False)),
                ('alarma_circulacion', models.BooleanField(default=False)),
                ('alarma_mantenimiento', models.BooleanField(default=False)),
                ('ultimo_evento_dt', models.DateTimeField(blank=True, null=True)),
                ('observaciones_servicio', models.CharField(default='sin observaciones', max_length=80)),
                ('vel', models.FloatField(blank=True, default=0, null=True)),
                ('lng', models.FloatField(default=-3.982)),
                ('lat', models.FloatField(default=40.2951)),
                ('km_totales', models.FloatField(default=0)),
                ('EEM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.eem')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.fabricante')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.keeper')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='organizaciones.owner')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.tipovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_particular', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.tiposistema')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='material.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaEAVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_particular', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('EAVM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='material.eavm')),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.tiposistema')),
            ],
        ),
        migrations.AddField(
            model_name='eavm',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ejes', to='material.vehiculo'),
        ),
        migrations.CreateModel(
            name='ConjuntoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_particular', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('num_unidades', models.IntegerField(default=0)),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.tipoconjunto')),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='material.sistemavehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ConjuntoEAVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_particular', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('num_unidades', models.IntegerField(default=0)),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.tipoconjunto')),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='material.sistemaeavm')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_unidades', models.IntegerField(default=0)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.tipocomponente')),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.conjuntovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteEAVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_unidades', models.IntegerField(default=0)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ingenieria.tipocomponente')),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.conjuntoeavm')),
            ],
        ),
    ]
