msg_circ = \
{
    "dt":"2022-11-03 12:00:00", 
    "tipo_msg":"CIRC",
    "vehiculo":1, 
    "lng":-1.7893, 
    "lat":43.3477,
    "vel":75.87,
    "msgs_ejes":
    [
        {
            "eje":"TR0001", 
            "tempa": 25.8,
            "tempb": 26.0, 
            "axMa": 2.1,
            "axmeda": 1.8,
            "fxa":12,
            "axMb":4.2,
            "axmedb":2.2,
            "fxb":11.5,
            "ayMa":3.4,
            "aymeda":3.4,
            "fya":12.3,
            "ayMb":1.2,
            "aymedb":3.0,
            "fyb":12.1,
            "azMa":5.2,
            "azmeda":5.0,
            "fza":10.3,
            "azMb":7.9,
            "azmedb":4.9,
            "fza":12.5
        },
        {
            "eje":"TR0002", 
            "tempa": 25.8,
            "tempb": 26.0, 
            "axMa": 2.1,
            "axmeda": 1.8,
            "fxa":12,
            "axMb":4.2,
            "axmedb":2.2,
            "fxb":11.5,
            "ayMa":3.4,
            "aymeda":3.4,
            "fya":12.3,
            "ayMb":1.2,
            "aymedb":3.0,
            "fyb":12.1,
            "azMa":5.2,
            "azmeda":5.0,
            "fza":10.3,
            "azMb":7.9,
            "azmedb":4.9,
            "fza":12.5
        },
        {
            "eje":"TR0003", 
            "tempa": 25.8,
            "tempb": 26.0, 
            "axMa": 2.1,
            "axmeda": 1.8,
            "fxa":12,
            "axMb":4.2,
            "axmedb":2.2,
            "fxb":11.5,
            "ayMa":3.4,
            "aymeda":3.4,
            "fya":12.3,
            "ayMb":1.2,
            "aymedb":3.0,
            "fyb":12.1,
            "azMa":5.2,
            "azmeda":5.0,
            "fza":10.3,
            "azMb":7.9,
            "azmedb":4.9,
            "fza":12.5
        },
        {
            "eje":"TR0004", 
            "tempa": 25.8,
            "tempb": 26.0, 
            "axMa": 2.1,
            "axmeda": 1.8,
            "fxa":12,
            "axMb":4.2,
            "axmedb":2.2,
            "fxb":11.5,
            "ayMa":3.4,
            "aymeda":3.4,
            "fya":12.3,
            "ayMb":1.2,
            "aymedb":3.0,
            "fyb":12.1,
            "azMa":5.2,
            "azmeda":5.0,
            "fza":10.3,
            "azMb":7.9,
            "azmedb":4.9,
            "fza":12.5
        }
    ]
}